'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('hello', '/handler.js', 'hello');

describe('hello', () => {
  before((done) => {
    done();
  });

  it('displays a friendly greeting message', async () => {
    const response = await wrapped.run({});
    const body = JSON.parse(response.body);

    expect(body.message).to.equal('Sam was here.');
  });

  it('displays a status code 200', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).to.equal(200);
  });

  it('displays URL query strings back to me', async () => {

    const name = 'Sam';

    const response = await wrapped.run({
      queryStringParameters: { name: name } 
    });

    const body = JSON.parse(response.body);
    expect(body.message).to.contain(`Sup ${name}`);

  })

  it('responds to POST requests', async () => {

    const food = 'muffins';

    const response = await wrapped.run({
      httpMethod: 'POST',
      authorizer: {},
      headers: {},
      body: { 
        message: 'You got post yo',
        food: food
      } 
    });

    const body = JSON.parse(response.body);
    expect(body.object).deep.to.contain({ food: food });
  })

  // it('returns a secret from AWS parameter store', async () => {

  // });

  xit('returns environment variables', () => {});
  xit('displays users username', () => {});

});
