service: serverless-first

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
exclude:
  - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: first-endpoint
          method: get
      - http:
          path: first-endpoint
          method: post
plugins:
  - serverless-offline
  - serverless-mocha-plugin